# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    container: 
      image: quay.io/pypa/manylinux2010_x86_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        /opt/python/cp39-cp39/bin/python -m pip install build twine
    - name: Build package
      run: /opt/python/cp39-cp39/bin/python -m build --sdist --wheel
    - name: Publish package
      run: |
        /opt/python/cp39-cp39/bin/python -m twine upload dist/*.tar.gz wheelhouse/*
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
